/* Gera docs/layout-ensaio/INVENTARIO.md a partir de inventario.json (checkpoint A, issue #457). Só lê o JSON. */
'use strict';
const fs = require('fs'), path = require('path');
const L = require('./lib.cjs');
const DIR = path.join(L.REPO, 'docs/layout-ensaio');
const inv = JSON.parse(fs.readFileSync(path.join(DIR, 'inventario.json'), 'utf8'));

const { agregadora, fcUnicos, qUnicos } = require('./derivar.cjs');
const SN = (b) => b ? 'SIM' : 'NÃO';

const L1 = [];
const w = s => L1.push(s);
const mats = inv.materias;
const tot = k => mats.reduce((a, m) => a + k(m), 0);

w('# Inventário real das matérias ativas · Checkpoint A · issue #457');
w('');
w(`> Gerado por \`tools/qa/ensaio-layout/inventario.cjs\` em ${inv.gerado_em.slice(0, 10)}. **Somente leitura**: nenhuma matéria, flag, UID ou arquivo de produção foi alterado; zero escritas no Supabase (simulado); zero rede externa.`);
w('> Medido no navegador, com o `app-core.js` real, **sem nada do layout novo** (a matéria como o site a serve hoje). Fonte do catálogo: `const CATALOGO` (index.html) × `FILES` (get-materia.js) × `netlify/functions/materias-privadas/`.');
w('');
w('## 1 · Reconciliação do catálogo (#366)');
const r = inv.reconciliacao;
w('');
w(`| Verificação | Resultado |`);
w(`|---|---|`);
w(`| Matérias ativas (catálogo ∩ \`FILES\`) | **${r.ativas}** |`);
w(`| Só no catálogo, sem arquivo servido | ${r.soNoCatalogo.length ? r.soNoCatalogo.join(', ') : 'nenhuma'} |`);
w(`| Só em \`FILES\`, fora do catálogo | ${r.soNoGetMateria.length ? r.soNoGetMateria.join(', ') : 'nenhuma'} |`);
w(`| Arquivo servido que não existe no disco | ${r.arquivosFaltando.length ? r.arquivosFaltando.join(', ') : 'nenhum'} |`);
w(`| Arquivos **órfãos** no disco (não servidos, fora do catálogo) | ${r.arquivosOrfaos.map(f => '`' + f + '`').join(', ')} |`);
w('');
w('Os 3 arquivos órfãos **não são matérias ativas** e ficam fora do ensaio (não há rota, nem `FILES`, nem entrada no catálogo): um aluno não os alcança. Não foram tocados.');
w('');
w('## 2 · Totais (27 matérias)');
w('');
w(`| Recurso | Total medido |`);
w(`|---|---:|`);
w(`| Blocos no índice (\`.rm-menu\`) | ${tot(m => m.particularidades.menuComAlvo)} |`);
w(`| Seções \`<section id>\` | ${tot(m => m.nSecoes)} |`);
w(`| Questões \`.quiz-item\` no DOM (somando cópias) | ${tot(m => m.questoes.total)} |`);
w(`| Questões **distintas** (por enunciado · por enunciado+opções) | ${tot(m => m.unicos.quiz)} · ${tot(m => m.unicos.quizComOpc)} |`);
w(`| Flashcards \`.flashcard\` no DOM (somando cópias) | ${tot(m => m.flashcards.total)} |`);
w(`| Flashcards **distintos** (pela frente) | ${tot(m => m.unicos.fc)} |`);
w(`| Figuras com legenda | ${tot(m => m.figuras)} |`);
w(`| Videoclases (\`details.video-collapsible\`) | ${tot(m => m.videos.cards)} |`);
w(`| Elementos \`<audio>\` (ausculta) | ${tot(m => m.ausculta.audios)} |`);
w(`| IDs duplicados | ${tot(m => m.idsDuplicados.length)} |`);
w(`| Mídia local quebrada | ${tot(m => m.midiaQuebrada.img.length + m.midiaQuebrada.audio.length + m.midiaQuebrada.video.length)} |`);
w(`| Erros de JavaScript no carregamento | ${tot(m => m.erros.length)} |`);
w(`| Requisições externas tentadas | ${tot(m => m.externas.length)} |`);
w(`| Escritas ao Supabase | ${tot(m => (m.escritas || []).length)} |`);
w('');
w('## 3 · Tabela por matéria');
w('');
w('Legenda: **Banco** = a matéria tem seção de Banco geral **reconhecida pelo nome do id** (heurística do piloto; o validador `contrato.cjs`, regra R4, detecta o Banco também por conteúdo e acrescenta Farmacología II, Embriología e Histología I, cujo Banco tem outro nome); **cópia** = como as questões do Banco casam com as do corpo (por `id` ou por enunciado). **ID q.** = quantas questões têm `id` próprio. **Áudio** = elementos `<audio>` no DOM de hoje (ausculta de Semiología), **não** audiobook.');
w('');
w('| Matéria (slug) | Arquivo | Seções | Blocos (índice) | q. DOM | q. distintas (enun. / +opc.) | q. Banco | Banco? | cópia | ID q. | Flashcards DOM / distintos | Figuras | Vídeos | Áudio |');
w('|---|---|--:|--:|--:|--:|--:|:-:|:-:|--:|--:|--:|--:|--:|');
mats.forEach(m => {
  const fu = fcUnicos(m); const q = m.questoes;
  const cop = q.banco ? (q.bancoOrfaos ? `⚠ ${q.bancoOrfaos} sem par` : (q.bancoCasaId ? 'por id' : 'por enunciado')) : '—';
  w(`| ${m.title} (\`${m.slug}\`) | \`${m.arquivo.nome}\` | ${m.nSecoes} | ${m.particularidades.menuComAlvo} | ${q.total} | **${m.unicos.quiz}**${m.unicos.quizComOpc !== m.unicos.quiz ? ' / ' + m.unicos.quizComOpc : ''} | ${q.banco} | ${SN(q.banco > 0)} | ${cop} | ${q.total - q.semId}/${q.total} | ${m.flashcards.total} / **${m.unicos.fc}** | ${m.figuras} | ${m.videos.cards} (${m.videos.iframes} iframe) | ${m.ausculta.audios} |`);
});
w('');
w('## 4 · Estados por matéria (SIM / NÃO / INDETERMINADO, com evidência)');
w('');
w('Critério: **SIM** = presente e medido no DOM; **NÃO** = ausente (contagem 0 no DOM real); **INDETERMINADO** = o DOM não permite concluir (explicado).');
w('');
w('| Matéria | Blocos numerados | Banco geral | Questões c/ ID | Flashcards | Figuras c/ legenda | Vídeos | Ausculta (`<audio>`) | Audiobook | Cover/portada | Evidência |');
w('|---|:-:|:-:|:-:|:-:|:-:|:-:|:-:|:-:|:-:|---|');
mats.forEach(m => {
  const q = m.questoes, p = m.particularidades; const fu = fcUnicos(m);
  const comId = q.total - q.semId; const idEst = comId === 0 ? 'NÃO' : (comId === q.total ? 'SIM' : 'PARCIAL');
  const portada = m.secoes.some(s => /portada|00$|intro|guia|inicio/i.test(s.id)) ;
  const ev = `seções=${m.nSecoes}; menu=${p.menuComAlvo}${p.semMenu.length ? ' (sem item: ' + p.semMenu.join(',') + ')' : ''}; q=${q.total} DOM/${m.unicos.quiz} distintas${qUnicos(m).copiaEm ? ' (agregadora ' + qUnicos(m).copiaEm + ')' : ''}; fc=${m.flashcards.total} DOM/${m.unicos.fc} distintos${fu.copiaEm ? ' (agregadora ' + fu.copiaEm + ')' : ''}; fig=${m.figuras}; vid=${m.videos.cards}; audio=${m.ausculta.audios}`;
  w(`| ${m.title} | ${SN(p.menuComAlvo > 0)} | ${SN(q.banco > 0)} | ${idEst} | ${SN(m.flashcards.total > 0)} | ${SN(m.figuras > 0)} | ${SN(m.videos.cards + m.videos.iframes + m.videos.nativos > 0)} | ${SN(m.ausculta.audios > 0)} | **NÃO** (sem manifesto) | ${portada ? 'SIM' : 'NÃO'} | ${ev} |`);
});
w('');
w('**Audiobook = NÃO em todas as 27**: o único manifesto autorizado hoje é o do piloto (Semiología II, via `get-audio-manifest`, atrás do flag `audio`). O inventário **não** consulta manifesto, não simula áudio e não lê Supabase. Os `<audio>` de Semiología e Semiología II são a **ausculta** (cards de sons clínicos), um recurso diferente do audiobook.');
w('');
w('## 5 · Contagens declaradas à mão × contagem canônica (veredito em CONFORMIDADE.md · R5)');
w('');
w('O texto da portada de cada matéria declara números («179 preguntas», «335 flashcards», «34 infografías»…), editados à mão. **Este inventário só mede; o veredito não está aqui.** Uma versão anterior desta seção (e da regra R5 do validador) dava «coincide» quando o número igualava *qualquer* contagem candidata, inclusive o total do DOM com cópias; isso foi **removido** porque aprovava por coincidência. A comparação correta é feita por `contrato.cjs` (regra **R5**): cada número declarado na portada contra a contagem **canônica** do recurso correspondente (itens distintos, fora das seções agregadoras). Ver `CONFORMIDADE.md`, quadro «R5».');
w('');
try {
  const cf = JSON.parse(fs.readFileSync(path.join(DIR, 'conformidade.json'), 'utf8'));
  const ds = cf.materias.flatMap(o => (o.detalhe.R5.det.itens || []).filter(i => i.estado !== 'fora-do-contrato'));
  const ok = ds.filter(i => i.estado === 'ok').length, dv = ds.filter(i => i.estado === 'diverge').length, ind = ds.filter(i => i.estado === 'indeterminado').length, so = ds.filter(i => i.soCoincideComDOM).length;
  w(`Resumo de R5 (conformidade.json): ${ds.length} números declarados na portada com recurso verificável · **${ok} iguais ao canônico** · **${dv} divergem** (${so} deles coincidem apenas com o total do DOM duplicado) · **${ind} indeterminados** (sem marcador nem convenção para contar).`);
} catch (e) { w('(Rode `contrato.cjs` para gerar o resumo de R5.)'); }
w('');
w('## 6 · Particularidades que afetam o novo layout');
w('');
const part = [];
mats.forEach(m => {
  const p = m.particularidades, q = m.questoes; const fu = fcUnicos(m);
  const l = [];
  if (p.semMenu.length) l.push(`seção(ões) sem item de índice: \`${p.semMenu.join('`, `')}\``);
  if (fu.copiaEm) l.push(`flashcards: seção agregadora \`${fu.copiaEm}\` repete os dos blocos (DOM ${m.flashcards.total}; distintos ${fu.unicos})`);
  else if (m.flashcards.total !== m.unicos.fc) l.push(`flashcards repetidos entre seções sem agregadora única (DOM ${m.flashcards.total}; distintos ${m.unicos.fc})`);
  if (qUnicos(m).copiaEm) l.push(`questões: seção \`${qUnicos(m).copiaEm}\` repete as dos blocos (DOM ${q.total}; distintas ${m.unicos.quiz})`);
  else if (q.total !== m.unicos.quiz) l.push(`questões repetidas entre seções (DOM ${q.total}; distintas ${m.unicos.quiz})`);
  if (q.semId === q.total && q.total) l.push('nenhuma questão tem `id`');
  else if (q.semId) l.push(`${q.semId}/${q.total} questões sem \`id\``);
  if (q.banco && q.bancoOrfaos) l.push(`${q.bancoOrfaos} questões do Banco sem par no corpo`);
  if (m.idsDuplicados.length) l.push(`IDs duplicados: ${m.idsDuplicados.slice(0, 5).join(', ')}`);
  const mq = m.midiaQuebrada; if (mq.img.length + mq.audio.length + mq.video.length) l.push(`mídia local quebrada: ${[...mq.img, ...mq.audio, ...mq.video].slice(0, 4).join(', ')}`);
  if (m.erros.length) l.push(`erros JS: ${m.erros.slice(0, 2).join(' | ')}`);
  if (p.hero || p.quizCards) l.push('usa marcação do piloto (`.s2-hero`/`.s2-quiz-card`)');
  if (m.ausculta.audios) l.push(`${m.ausculta.audios} <audio> (ausculta)`);
  if (l.length) part.push(`- **${m.title}** (\`${m.slug}\`): ${l.join(' · ')}.`);
});
part.forEach(w);
w('');
w('## 7 · O que este inventário NÃO conclui');
w('');
w('- Não avalia qualidade científica/didática de nenhuma matéria (fora do escopo da #457).');
w('- «Questões distintas» tem dois critérios porque **o DOM não traz um identificador estável** na maioria das matérias: por enunciado (piso; junta perguntas diferentes com o mesmo enunciado genérico) e por enunciado+opções (teto; separa cópias do Banco reescritas). Quando os dois divergem, a contagem exata é **INDETERMINADA** sem `id`; é exatamente o que o contrato do checkpoint C resolve.');
w('- «Questões c/ ID» mede o atributo `id` do `.quiz-item`; matérias sem `id` não são defeito do layout, mas **impedem rastrear** o par corpo×Banco por id (o casamento é por enunciado).');
w('- «Figuras c/ legenda» conta `<figure>` com `<figcaption>` e imagem; infográficos sem legenda ou fora de `<figure>` não entram (INDETERMINADO quanto a «34 infografías» declaradas).');
w('- Existência de arquivos de mídia foi verificada só para caminhos **relativos**; URLs absolutas (YouTube) não foram acessadas.');
fs.writeFileSync(path.join(DIR, 'INVENTARIO.md'), L1.join('\n') + '\n');
console.log('INVENTARIO.md', L1.length, 'linhas');
