/* Gera docs/caneta-456/METRICAS.md a partir de docs/caneta-456/dados/{antes,depois,antes-celular,depois-celular}.json (saída de medir.cjs). Uso: node tools/qa/caneta-456/relatorio.cjs */
'use strict';
const fs = require('fs'), path = require('path');
const D = path.resolve(__dirname, '../../../docs/caneta-456'), ler = f => { try { return JSON.parse(fs.readFileSync(path.join(D, 'dados', f), 'utf8')); } catch (e) { return null; } };
const A = ler('antes.json'), P = ler('depois.json'), AC = ler('antes-celular.json'), PC = ler('depois-celular.json');
if (!A || !P) { console.error('faltam dados/antes.json e dados/depois.json'); process.exit(1); }
const f = x => x == null ? '–' : String(x), pct = (a, b) => (a && b != null ? (b <= a ? '−' : '+') + Math.abs(Math.round((b - a) / a * 100)) + '%' : '–');
const L = [];
L.push('# Métricas antes/depois · #456 P0 (Chromium, motor REAL — **emulação, não aparelho real**)', '');
L.push(`Antes = \`${A.ref}\` · Depois = ${P.ref} · medido em ${P.quando}. CPU 1× (trace) ou 4×/6× (\`Emulation.setCPUThrottlingRate\`: aproxima um tablet, não o substitui). Medianas de ${(A.porTraco.novo || {}).n || 3} execuções independentes (o harness varia ±20–30% entre execuções; o que decide é a ordem de grandeza e as medidas determinísticas — contagem de elementos recalculados).`, '');
L.push('## A · Custo POR TRAÇO — recálculo de estilo no pointerdown e no pointerup (trace, CPU 1×, toolbox aberta, lápis armado)', '', '| layout | evento | elementos reaplicados (antes → depois) | maior recálculo, ms (antes → depois) | soma de estilo, ms (antes → depois) |', '|---|---|---|---|---|');
for (const c of ['antigo', 'novo']) for (const e of ['down', 'up']) { const a = A.porTraco[c][e], p = P.porTraco[c][e]; L.push(`| ${c} | ${e === 'down' ? 'pointerdown' : 'pointerup'} | ${f(a.elementos)} → **${f(p.elementos)}** | ${f(a.estiloMax)} → **${f(p.estiloMax)}** | ${f(a.estiloMs)} → **${f(p.estiloMs)}** |`); }
L.push('', 'Causa: `body.rm2-t-pen.rm2-pen-down #materias-container{touch-action:none}` — `touch-action` efetivo é herdado; mudá-lo no contêiner reaplica o estilo a **todos** os descendentes, 2 vezes por letra. A 6–10× de CPU de um tablet isso são 100–200 ms **por letra**, antes mesmo de a tinta aparecer.', '');
L.push('## B · Escrita DURANTE o traço (bancada do #461, CPU 4×, toolbox aberta, lápis armado, 360/200 pontos)', '', '| layout · gesto | maior quadro, ms (antes → depois) | quadros > 50 ms | tarefas longas (n · máx ms) | entrega p95, ms | tinta p95, ms | pontos perdidos | desvio máx, px |', '|---|---|---|---|---|---|---|---|');
for (const k of Object.keys(A.escrita)) { const a = A.escrita[k], p = P.escrita[k]; L.push(`| ${k} | ${f(a.quadroMax)} → **${f(p.quadroMax)}** | ${f(a.mais50)} → **${f(p.mais50)}** | ${f(a.tarefasLongas)} · ${f(a.tarefasLongasMax)} → **${f(p.tarefasLongas)} · ${f(p.tarefasLongasMax)}** | ${f(a.entregaP95)} → ${f(p.entregaP95)} | ${f(a.tintaP95)} → ${f(p.tintaP95)} | ${f(a.perdidos)} → ${f(p.perdidos)} | ${f(a.maxDistPx)} → ${f(p.maxDistPx)} |`); }
L.push('', 'Leitura: o intervalo entre quadros no MEIO do traço (≈ 17 ms) já era bom nos dois layouts — o atraso medido estava no **começo** de cada traço (o pointerdown bloqueava a thread principal de 100 a 180 ms a 4×; 2 tarefas longas por traço) e no **fim** (pointerup). Depois: 0 quadros > 50 ms e 0 tarefas longas.', '');
if (AC && PC) {
  L.push('## B2 · Celular 390×844 (DPR 2, CPU 6×, toolbox aberta, lápis armado, gesto rápido)', '', '| layout | maior quadro, ms (antes → depois) | quadros > 50 ms | tarefas longas (n · máx ms) | pontos perdidos |', '|---|---|---|---|---|');
  for (const c of ['antigo', 'novo']) { const a = AC.celular[c], p = PC.celular[c]; L.push(`| ${c} | ${f(a.quadroMax)} → **${f(p.quadroMax)}** | ${f(a.mais50)} → **${f(p.mais50)}** | ${f(a.tarefasLongas)} · ${f(a.tarefasLongasMax)} → **${f(p.tarefasLongas)} · ${f(p.tarefasLongasMax)}** | ${f(a.perdidos)} → ${f(p.perdidos)} |`); }
  L.push('');
}
L.push('## C · Trocar de bloco/modo no piloto novo (CPU 4×; toolbox ABERTA + lápis armado + traço recém-feito, e toolbox FECHADA)', '', '| estado · transição | até o 2.º quadro, ms (antes → depois) | CPU total da transição, ms (antes → depois) | tarefa longa máx, ms (antes → depois) |', '|---|---|---|---|');
for (const e of Object.keys(A.trocas)) for (const t of [['modoIda', 'bloco → modo'], ['modoVolta', 'modo → bloco'], ['blocoBloco', 'bloco ↔ bloco']]) { const a = A.trocas[e][t[0]], p = P.trocas[e][t[0]]; L.push(`| ${e} · ${t[1]} | ${f(a.mediana)} → **${f(p.mediana)}** (${pct(a.mediana, p.mediana)}) | ${f(a.cpuMs)} → **${f(p.cpuMs)}** | ${f(a.tarefasLongasMax)} → **${f(p.tarefasLongasMax)}** |`); }
L.push('', '> Nota (ruído): a linha «fechada · modo → bloco» varia ±25–50% entre execuções do harness (ordem de execução, CPU compartilhada). Com 6 medições **intercaladas** antes/depois nessa mesma transição (`dados/intercalado-fechada-modo-bloco.json`) a média é 473 ms (antes) × 468 ms (depois): **sem diferença** — e as medidas determinísticas abaixo (C2) são idênticas (1 passe grande, ≈ 3 620 elementos). O que muda de verdade é o caso com a toolbox ABERTA.');
L.push('', '### C2 · Medida DETERMINÍSTICA (não depende de tempo): recalculações de estilo de ≥ 800 elementos numa ida e volta de modo (CPU 1×)', '', '| estado | passes grandes por ida e volta (antes → depois) | elementos reaplicados (antes → depois) | tempo de estilo, ms (antes → depois) |', '|---|---|---|---|');
for (const e of Object.keys(A.trocas)) { const a = A.trocas[e].estiloGrandes, p = P.trocas[e].estiloGrandes; L.push(`| ${e} | ${f(a.passesPorIdaVolta)} → **${f(p.passesPorIdaVolta)}** | ${f(a.elementosPorIdaVolta)} → **${f(p.elementosPorIdaVolta)}** | ${f(a.msPorIdaVolta)} → **${f(p.msPorIdaVolta)}** |`); }
L.push('', 'Causa: `rm-materia-sistema.js` (`sync` do espelho da toolbox) escrevia `--rm-dock-h` na `<html>` toda vez que a caixa aparecia/sumia com a vista. Com a toolbox aberta, cada ida e volta de modo mudava o valor **duas vezes** (ocultar → 0, mostrar → altura) e cada mudança de uma variável herdada reaplica o estilo da página inteira (a segunda passada grande, ~120 ms a 4×, ~400 ms depois da troca — a «breve travada»). O CSS só usa a variável < 768 px.', '');
L.push('## Limites', '', '- Emulação no Chromium sobre CPU de servidor (rápida). Nenhum número aqui substitui o aparelho real do José; o teste de ≤ 3 min (`PASSO-FINAL-JOSE.md`) mede os mesmos itens no tablet.', '- O custo-base de trocar de bloco/modo (mostrar/ocultar ~1 200–2 400 elementos) continua: é o preço de exibir outro bloco. O que saiu foi o excesso medido da toolbox aberta.', '- Pontos perdidos = 0 antes e depois (rajadas, sem ack): se o aparelho real cortar o traço (pointercancel/captura perdida) isso só aparece no diagnóstico opt-in.');
fs.writeFileSync(path.join(D, 'METRICAS.md'), L.join('\n') + '\n'); console.log('METRICAS.md escrito');
